"use client";

import { ReactNode } from 'react';
import { ArrowLeft, Share2, Download } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { motion } from 'framer-motion';

interface UniformLayoutProps {
  title: string;
  subtitle?: string;
  location?: string;
  children: ReactNode;
  tabs?: Array<{
    id: string;
    label: string;
    icon: ReactNode;
    active?: boolean;
    onClick: () => void;
  }>;
  actions?: ReactNode;
}

export default function UniformLayout({ 
  title, 
  subtitle, 
  location, 
  children, 
  tabs, 
  actions 
}: UniformLayoutProps) {
  const router = useRouter();

  const handleShare = async () => {
    const shareData = {
      title: title,
      text: subtitle || `Business analysis for ${title}`,
      url: window.location.href
    };

    try {
      if (navigator.share) {
        await navigator.share(shareData);
      } else {
        // Fallback: copy to clipboard
        await navigator.clipboard.writeText(window.location.href);
        alert('Link copied to clipboard!');
      }
    } catch (error) {
      console.error('Error sharing:', error);
      // Fallback: copy to clipboard
      try {
        await navigator.clipboard.writeText(window.location.href);
        alert('Link copied to clipboard!');
      } catch (clipboardError) {
        console.error('Clipboard error:', clipboardError);
      }
    }
  };

  const handleDownload = () => {
    // Create a simple text report
    const reportContent = `
Business Analysis Report
========================

Title: ${title}
${subtitle ? `Subtitle: ${subtitle}` : ''}
${location ? `Location: ${location}` : ''}
Generated: ${new Date().toLocaleDateString()}
URL: ${window.location.href}

This report was generated by your business analysis platform.
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_report.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-[#020617] transition-colors duration-500">
      {/* Header - Professional Static Flow */}
      <div className="relative z-40 bg-white dark:bg-[#0a0f25] border-b border-slate-200 dark:border-white/5 shadow-sm">
        <div className="responsive-container py-8 md:py-12">
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-8">
            <div className="flex flex-col md:flex-row md:items-center gap-6 md:gap-10">
              <button
                onClick={() => router.push('/dashboard')}
                className="shrink-0 flex items-center space-x-3 text-slate-500 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white transition-all group"
              >
                <div className="w-10 h-10 rounded-xl bg-slate-100 dark:bg-white/5 flex items-center justify-center group-hover:bg-slate-200 dark:group-hover:bg-white/10 transition-all border border-slate-200/50 dark:border-white/10">
                  <ArrowLeft size={18} />
                </div>
                <span className="text-xs font-black uppercase tracking-[0.2em] italic">Back</span>
              </button>
              
              <div className="hidden md:block h-16 w-px bg-slate-200 dark:bg-white/10" />
              
              <div className="space-y-2">
                <h1 className="text-2xl sm:text-4xl lg:text-5xl font-black text-slate-900 dark:text-white tracking-tighter leading-none italic uppercase">
                  {title}
                </h1>
                <div className="flex flex-wrap items-center gap-x-4 gap-y-2">
                  {subtitle && (
                    <p className="text-sm sm:text-base font-bold text-slate-500 dark:text-gray-400 uppercase tracking-widest opacity-80">
                      {subtitle}
                    </p>
                  )}
                  {location && (
                    <div className="flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-500/5 border border-emerald-500/20">
                      <span className="w-1.5 h-1.5 bg-emerald-500 rounded-full animate-pulse shadow-[0_0_8px_rgba(16,185,129,0.6)]"></span>
                      <span className="text-[10px] sm:text-xs font-black text-emerald-600 dark:text-emerald-400 uppercase tracking-widest">{location}</span>
                    </div>
                  )}
                </div>
              </div>
            </div>
            
            <div className="flex items-center gap-3">
              {actions}
              <div className="h-10 w-px bg-slate-200 dark:bg-white/10 mx-1 hidden sm:block" />
              <button 
                onClick={handleShare}
                className="w-12 h-12 flex items-center justify-center bg-slate-100 dark:bg-white/5 hover:bg-slate-200 dark:hover:bg-white/10 rounded-xl text-slate-600 dark:text-gray-400 hover:text-slate-900 dark:hover:text-white transition-all border border-slate-200 dark:border-white/10 shadow-sm"
                title="Share this page"
              >
                <Share2 size={18} />
              </button>
              <button 
                onClick={handleDownload}
                className="w-12 h-12 flex items-center justify-center bg-slate-100 dark:bg-white/5 hover:bg-slate-200 dark:hover:bg-white/10 rounded-xl text-slate-600 dark:text-gray-400 hover:text-slate-900 dark:hover:text-white transition-all border border-slate-200 dark:border-white/10 shadow-sm"
                title="Download report"
              >
                <Download size={18} />
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* Navigation Tabs - Static Flow */}
      {tabs && (
        <div className="relative z-30 bg-white dark:bg-[#0a0f25] border-b border-slate-200 dark:border-white/5">
          <div className="responsive-container">
            <div className="flex space-x-6 sm:space-x-8 overflow-x-auto scrollbar-hide">
              {tabs.map((tab) => (
                <button
                  key={tab.id}
                  onClick={tab.onClick}
                  className={`flex items-center space-x-2 py-3 sm:py-4 px-1 border-b-2 transition-all whitespace-nowrap ${
                    tab.active
                      ? 'border-emerald-500 text-emerald-600 dark:text-emerald-400'
                      : 'border-transparent text-slate-500 dark:text-gray-500 hover:text-slate-700 dark:hover:text-gray-300 hover:border-slate-300 dark:hover:border-white/20'
                  }`}
                >
                  <span className="flex-shrink-0">{tab.icon}</span>
                  <span className="font-medium text-sm sm:text-base">{tab.label}</span>
                </button>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* Content Area */}
      <div className="responsive-container py-8 sm:py-12 lg:py-16">
        {children}
      </div>
    </div>
  );
}